image: ruby:2.7.4

pipelines:
  default:
   - step:
        name: Rspec
        caches:
          - bundler
        script:
          - apt-get update
          - apt-get install -y build-essential libpq-dev nodejs
          - cp config/database.yml.ci config/database.yml
          - export RAILS_ENV=test
          - bundle install -j 5 --path vendor/bundle
          - bundle exec rails db:schema:load
          - bundle exec rspec
        services:
          - postgres

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: 'postgres'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
  caches:
    bundler: vendor/bundle
